
[[headers]]
  for = "/*"
  [headers.values]

  # Cache Control
  cache-control = "public, max-age=3600"

  # Strict Transport Security (HSTS)
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

  # XSS Protection
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"

  # Clickjacking Protection
  X-Frame-Options = "DENY"

  # Referrer Policy
  Referrer-Policy = "strict-origin-when-cross-origin"
  Feature-Policy = "geolocation 'none'; camera 'none';"

  Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=()"
  Content-Security-Policy = """
      default-src 'self';
      base-uri 'self';
      object-src 'none';
      frame-ancestors 'none';
      form-action 'self';
      img-src 'self' data: https:;
      script-src 'self';
      style-src 'self' 'unsafe-inline';
      connect-src 'self' https:;
      font-src 'self' https:;
      upgrade-insecure-requests
    """

[[redirects]]
from = "https://www.crypto-horizon-app.netlify.app/*"
to = "https://crypto-horizon-app.netlify.app/:splat"
status = 301
force = true


[images]
remote_images = [
    "https://lcw.nyc3.cdn.digitaloceanspaces.com/.*",
    "https://coin-images.coingecko.com/.*",
    "https://res.cloudinary.com/.*",
    "https://resources.cryptocompare.com/.*",
    "https://images.cryptocompare.com/.*",
    "https://www.coingecko.com/.*",
]