
[images]
remote_images = [
  "https://lcw.nyc3.cdn.digitaloceanspaces.com/.*",
  "https://coin-images.coingecko.com/.*",
  "https://res.cloudinary.com/.*",
  "https://resources.cryptocompare.com/.*",
  "https://images.cryptocompare.com/.*",
  "https://www.coingecko.com/.*",
  "https://www.coingecko.com/coins/.*",
  "https://www.coingecko.com/nft/.*",
]

[[headers]]
  for = "/*"
  [headers.values]
  cache-control = "public, max-age=86400"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Feature-Policy = "geolocation 'none'; camera 'none';"